export const metadata = {
    title: "cart",
    description: "Generated by create next app",
  };
export default function Layout({ children }) {
    return (
      <>
        {children}
      </>
    )
  }